server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    druid:
      db-type: com.cc.druid.pool.DruidDataSoure
      url: jdbc:mysql:///sm_db
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  type-aliases-package: com.cc.pojo
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: isDeleted
      id-type: auto
      table-prefix: news_

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义




